<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/Broadcasting%2Cstatistical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

25/08

In [ ]:
import numpy as np
arr1=np.arange(1,4)
arr2=np.arange(1,10).reshape(3,3)
arr1,arr2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [ ]:
arr1+arr2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
arr3=np.arange(1,4)
arr4=np.arange(4,7).reshape(3,1)
arr3,arr4

(array([1, 2, 3]),
 array([[4],
        [5],
        [6]]))

In [ ]:
#elementwise multiplication
arr3*arr4

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [ ]:
arr5=np.array(5)
arr6=np.arange(1,21).reshape(4,5)
arr5,arr6

(array(5),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [ ]:
arr5/arr6

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ],
       [0.        , 0.08333333, 0.15384615, 0.21428571, 0.26666667],
       [0.        , 0.05882353, 0.11111111, 0.15789474, 0.2       ]])

In [ ]:
import numpy as np
arr7=np.arange(1,3)
arr8=np.arange(1,13).reshape(4,3)
arr7,arr8

(array([1, 2]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [ ]:
arr9=np.random.randint(1,10,(2,3,4))
arr10=np.random.randint(1,10,(3))
arr9,arr10

(array([[[8, 8, 7, 9],
         [5, 1, 7, 4],
         [3, 6, 8, 6]],
 
        [[8, 1, 6, 6],
         [9, 8, 8, 1],
         [6, 3, 2, 5]]]),
 array([4, 2, 3]))

In [ ]:
statistical operations

statistical operations

In [ ]:
np.random.seed(42)
arr1=np.random.randint(1,10,(10,1))
arr1

array([[7],
       [4],
       [8],
       [5],
       [7],
       [3],
       [7],
       [8],
       [5],
       [4]])

mean

In [ ]:
#function
np.mean(arr1)

np.float64(5.8)

In [ ]:
#method
arr1.mean()

np.float64(5.8)

In [ ]:
'mean' in dir(np)

True

In [ ]:
'mean' in dir(np.ndarray) #method

True

median

In [ ]:
#function
np.median(arr1)

np.float64(6.0)

In [ ]:
#method
arr1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
'mode' in dir(np)

False

In [ ]:
'mode'in dir(np.ndarray)

False

variance

-population variance

In [ ]:
np.var(arr1)

np.float64(2.96)

In [ ]:
arr1.var()

np.float64(2.96)

standard deviation

.population standard deviation

In [ ]:
np.std(arr1)

np.float64(1.7204650534085253)

In [ ]:
arr1.std()

np.float64(1.7204650534085253)

quantiles

-25% and 75% are convention followed by statisticians.based on our data we can change Q1 and Q3 to any other

In [ ]:
np.percentile(arr1,0.25) #q1

np.float64(3.0225)

In [ ]:
np.percentile(arr1,0.75) #q2

np.float64(3.0675)

In [ ]:
'skew'in dir(np)

False

In [ ]:
'kurt' in dir(np)

False

In [ ]:
'kurt' in dir(np.ndarray)

False

maximum

In [ ]:
arr1

array([[7],
       [4],
       [8],
       [5],
       [7],
       [3],
       [7],
       [8],
       [5],
       [4]])

In [ ]:
np.max(arr1)

np.int64(8)

In [ ]:
arr1.max()

np.int64(8)

In [ ]:
#position of maximum element in arr1
np.argmax(arr1)

np.int64(2)

In [ ]:
arr1.argmax()

np.int64(2)

minimum

In [ ]:
arr1

array([[7],
       [4],
       [8],
       [5],
       [7],
       [3],
       [7],
       [8],
       [5],
       [4]])

In [ ]:
np.min(arr1)

np.int64(3)

In [ ]:
arr1.min()

np.int64(3)

In [ ]:
np.argmax(arr1)

np.int64(2)

In [ ]:
arr1.argmax()

np.int64(2)

sum

In [ ]:
np.sum(arr1)

np.int64(58)

In [ ]:
arr1.sum()

np.int64(58)

2D array

In [ ]:
np.random.seed(42)
arr2=np.random.randint(1,10,(4,5))
arr2

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4],
       [8, 8, 3, 6, 5],
       [2, 8, 6, 2, 5]])

sum

In [ ]:
np.sum(arr2)


np.int64(111)

In [ ]:
arr2.sum()

np.int64(111)

sum of elements in the rows-column direction

In [ ]:
np.sum(arr2,axis=0)

array([20, 27, 25, 18, 21])

In [ ]:
arr2.sum(axis=0)

array([20, 27, 25, 18, 21])

sum of elements in the column-row direction

In [ ]:
np.sum(arr2,axis=0)

array([20, 27, 25, 18, 21])

In [ ]:
arr2.sum(axis=1)

array([31, 27, 30, 23])

mean/meadian/var/std/max/min of arr2

-row mean/median/var/std/max/min of arr2

-column mean/median/var/std/max/min af arr2

In [ ]:
arr2.mean()

np.float64(5.55)

In [ ]:
arr2.mean(axis=1)

array([6.2, 5.4, 6. , 4.6])

In [ ]:
arr2.mean(axis=0)

array([5.  , 6.75, 6.25, 4.5 , 5.25])

In [ ]:
arr2.max()

np.int64(8)

In [ ]:
arr2.max(axis=0)

array([8, 8, 8, 6, 7])

In [ ]:
arr2.min()

np.int64(2)

In [ ]:
arr2.min(axis=1)

array([4, 3, 3, 2])

In [ ]:
arr2.min(axis=0)

array([2, 4, 3, 2, 4])

Data Collection

-empty cell or null or none in the data

-while converting to array or datafree

-empty cell or null or none are converted to nan

-to create naN manually use np.nan

In [ ]:
arr3=np.array([[1,np.nan,3],[np.nan,5,6],[7,8,np.nan]])
arr3

array([[ 1., nan,  3.],
       [nan,  5.,  6.],
       [ 7.,  8., nan]])

In [ ]:
arr3.sum()

np.float64(nan)

In [ ]:
arr3.sum(axis=1)

array([nan, nan, nan])

In [ ]:
arr3.sum(axis=0)

array([nan, nan, nan])

np.nan is a float64

-all the elements os array-type promoted to float64

In [ ]:
np.nansum(arr3)

np.float64(30.0)

In [ ]:
np.nansum(arr3,axis=1)

array([ 4., 11., 15.])

In [ ]:
np.nansum(arr3,axis=0)

array([ 8., 13.,  9.])

In [ ]:
np.nanmean(arr3)

np.float64(5.0)

In [ ]:
np.nanmean(arr3,axis=1)

array([2. , 5.5, 7.5])

In [ ]:
np.nanmean(arr3,axis=0)

array([4. , 6.5, 4.5])

In [ ]:
np.nanvar(arr3,axis=1)

array([1.  , 0.25, 0.25])

In [ ]:
np.nanstd(arr3,axis=1)

array([1. , 0.5, 0.5])

In [ ]:
np.nanmax(arr3,axis=1)

array([3., 6., 8.])

In [ ]:
np.nanmin(arr3,axis=1)

array([1., 5., 7.])

In [ ]:
np.nanargmax(arr3,axis=1)

array([2, 2, 1])

In [ ]:
np.nanmedian(arr3,axis=1)

array([2. , 5.5, 7.5])