<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/index%26slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

20/08

indexing and slicing

In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr1=np.arange(1,7)
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
'__getitem__' in dir(arr1)


True

In [ ]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [ ]:
#get element 3-single element-indexing
arr1[2]

np.int64(3)

In [ ]:
type(arr1[2])

numpy.int64

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
#get element 1,3,5-multiple elements-slicing
arr1[0:4+1:2]

array([1, 3, 5])

In [ ]:
type(arr1[0:4+1:2])

numpy.ndarray

slicing is indexing of slice object

In [ ]:
"__getitem__"(slicing)

.get the size of array

.fid its factor

In [ ]:
arr1=np.arange(1,5)
arr1

array([1, 2, 3, 4])

size-number of elements in an array

In [ ]:
arr1.size

4

In [ ]:
#4-1*4-(1,4)
arr_new=arr1.reshape(1,4)
arr_new,arr_new.shape

(array([[1, 2, 3, 4]]), (1, 4))

In [ ]:
#reshape funtion-rarely
arr_new=np.reshape(arr1,(1,4))
arr_new,arr_new.shape

(array([[1, 2, 3, 4]]), (1, 4))

In [ ]:
#4-4*1-(4,1)
arr_new=arr1.reshape(4,1)
arr_new,arr_new.shape

(array([[1],
        [2],
        [3],
        [4]]),
 (4, 1))

In [ ]:
#4-2*2-(2,2)
arr_new=arr1.reshape(2,2)
arr_new,arr_new.shape

(array([[1, 2],
        [3, 4]]),
 (2, 2))

In [ ]:
#4-1*1*4-(1,1,4)
arr_new=arr1.reshape(1,1,4)
arr_new,arr_new.shape

(array([[[1, 2, 3, 4]]]), (1, 1, 4))

In [ ]:
#4-1*4*1-(1,4,1)
arr_new=arr1.reshape(1,4,1)
arr_new,arr_new.shape

(array([[[1],
         [2],
         [3],
         [4]]]),
 (1, 4, 1))

In [ ]:
#4-2*2*1-(2,2,1)
arr_new=arr1.reshape(2,2,1)
arr_new,arr_new.shape

(array([[[1],
         [2]],
 
        [[3],
         [4]]]),
 (2, 2, 1))

In [ ]:
arr2=np.arange(1,21)
arr2,arr2.shape,arr2.size

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 (20,),
 20)

In [ ]:
arr2.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#(2,-1) numpy calculate the value at -1 as 10
arr2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#(4,5)
arr2.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#(4,-1)
arr2.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#(-1,5)
arr2.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#(2,5,2)
arr2.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [ ]:
#(2,-1,2)
arr2.reshape(2,-1,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [ ]:
#(1,2,2,5)
arr2.reshape(1,2,2,5)

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

resize


In [ ]:
np.resize(arr2,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.resize(arr2,(5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5]])

In [ ]:
arr3=np.arange(1,51)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
import numpy as np
arr3=np.arange(1,51).reshape(1,1,5,5,2)
arr3

array([[[[[ 1,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8],
          [ 9, 10]],

         [[11, 12],
          [13, 14],
          [15, 16],
          [17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24],
          [25, 26],
          [27, 28],
          [29, 30]],

         [[31, 32],
          [33, 34],
          [35, 36],
          [37, 38],
          [39, 40]],

         [[41, 42],
          [43, 44],
          [45, 46],
          [47, 48],
          [49, 50]]]]])

indexing of 2d arrays

In [ ]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#get element 7
arr1[2,0]

np.int64(7)

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#get element 6
arr1[1,2]

np.int64(6)

In [ ]:
arr2=np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arr2[rR,rR]-arr2[R(si:ei+1:step),c(si:ei+1:step)]

In [ ]:
#get element4,5
arr2[1:1+1,0:1+1]#arr2[rR,cR]

array([[4, 5]])

In [ ]:
#get element 5,8
arr2[1:2+1,0:1+1] #arr2[rR,cR]

array([[4, 5],
       [7, 8]])

In [ ]:
#get element 5,8
arr2[1:2+1,1] #[rR,cI]

array([5, 8])

In [ ]:
#GET 1ST ROW-(ROW WITH INDEX 0)
arr2[0:1,:] #arr2[rR,cR]

array([[1, 2, 3]])

In [ ]:
arr2[0,:]#arr2[rI,cR]

array([1, 2, 3])

In [ ]:
arr2[0:1]#arr2[rI,cR]

array([[1, 2, 3]])

In [ ]:
arr2[0]#arr2[rI,cR(IMPLICIT)]

array([1, 2, 3])

In [ ]:
arr2[0:3,1:2]


array([[2],
       [5],
       [8]])

In [ ]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
arr1[0:1,0:3]

array([[1, 2, 3]])

21/08

get the 1st row

In [ ]:
arr1[0:1,0:3]

array([[1, 2, 3]])

In [ ]:
arr1[0,:]

array([1, 2, 3])

In [ ]:
arr1[0:1]

array([[1, 2, 3]])

In [ ]:
arr1[0]

array([1, 2, 3])

get the 1st and 3rd rows

In [ ]:
arr1[0:3:2,0:3]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr1[0:3:2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr1[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

get the 2nd and 3rd column

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[0:3,1:2] #arr1[rR,cR]-2d array

array([[2],
       [5],
       [8]])

In [ ]:
arr1[:,1] #arr1[rR,cI]-1d array

array([2, 5, 8])

scalar

get 5-5,[5],[[5]]

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
a=np.array(5)
a

array(5)

In [ ]:
arr1[1,1]

np.int64(5)

In [ ]:
a=np.array([5])
a

array([5])

In [ ]:
arr1[1:2,1]

array([5])

In [ ]:
a=np.array([[5]])
print(a)

[[5]]


In [ ]:
arr1[1:2,1:2]

array([[5]])

In [ ]:
arr1[0:1,1:2]

array([[2]])

get elements[1,5,9]

.cannot extract thriugh slicing

In [ ]:
arr1[np.array([0,1,2]), np.array([0,1,2])]


array([1, 5, 9])

In [ ]:
arr1[[1,0,2],[2,1,0]]

array([6, 2, 7])

boolean indexing or masking

In [ ]:
arr1=np.arange(1,7)
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1[[False,True,False,True,False,True]]

array([2, 4, 6])

GET [1,3,5]

In [ ]:
arr1[[True,False,True,False,True,False]]

array([1, 3, 5])

get even numbers from array

In [ ]:
arr2=np.arange(1,101)
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

VECTORIZATION

.We apply an operation on n array,the operation is applied on every element on an array

.it is efficient alternative to LOOPS(while/for)

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1%2==0 #1%2==0,2%2==0,3%2==0,4%2==0-vectorization

array([False,  True, False,  True, False,  True])

In [ ]:
arr1[[False,True,False,True,False,True]]

array([2, 4, 6])

In [ ]:
arr1[arr1%2==0]

array([2, 4, 6])

get the even numbers from array

In [ ]:
arr2=np.arange(1,101)
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr2[arr2%2==0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
arr2[arr2%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Get the numbers divisible by 3

In [ ]:
arr2[arr2%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Get the numbers divisible by 5

In [ ]:
arr2[arr2%5==0]

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

to combine multiple condition

-use only operator symbol '&' for and i for or

-always enclose conditions in parenthesis(condition)

Get the numbers divisible by  either  3 and 5


In [ ]:
arr2[(arr2%3==0)|(arr2%5==0)]

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

Get the numbers divisible by both 3 and 5

In [ ]:
arr2[(arr2%3==0)&(arr2%5==0)]

array([15, 30, 45, 60, 75, 90])

get the numbers between 1,100.  neither divisible by 3 nor divisible by 5

In [ ]:
arr2[~((arr2%3==0)|(arr2%5==0))]

array([ 1,  2,  4,  7,  8, 11, 13, 14, 16, 17, 19, 22, 23, 26, 28, 29, 31,
       32, 34, 37, 38, 41, 43, 44, 46, 47, 49, 52, 53, 56, 58, 59, 61, 62,
       64, 67, 68, 71, 73, 74, 76, 77, 79, 82, 83, 86, 88, 89, 91, 92, 94,
       97, 98])

updation od arrays

In [ ]:
'__setitem__' in dir(np.ndarray)

True

In [ ]:
arr1=np.array([1,2,30,4,5])
arr1

array([ 1,  2, 30,  4,  5])

In [ ]:
arr1[2]

np.int64(30)

'__setitem__ 'is available,assign a value to it

In [ ]:
import numpy as np
arr2=np.array([[10,20],[30,40]])
arr2[1,1]=50
arr2

array([[10, 20],
       [30, 50]])

In [ ]:
#update  5 with 50
arr2[1,1]

np.int64(50)

In [ ]:
arr2[1,1]=50
arr2

array([[10, 20],
       [30, 50]])

broadcasting

In [ ]:
arr2[0]=30 #arr2[0]=[30,30,30]
arr2

array([[30, 30],
       [30, 50]])

updated [[50,60],[80,90]]to [[5,6],[8,9]]

In [ ]:
arr2[1:3,1:3]

array([[50]])

In [ ]:
arr2[1:3,1:3]=[[5,6],[8,9]]
arr2

ValueError: could not broadcast input array from shape (2,2) into shape (1,1)

inserting element or row or column to 1D or 2D arrays

.np.insert()

.np.insert do not modify exixting array,creates a new copy of it

In [ ]:
arr3=np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.insert(arr3,0,0) #insert an element 0 at index 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#insert an element 100 at index 5
np.insert(arr3,5,100)

array([  1,   2,   3,   4,   5, 100,   6,   7,   8,   9,  10])

In [ ]:
arr4=np.arange(1,10).reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.insert(arr4,3,[10,11,12])#add a row at the end of array[10,11,12]

array([ 1,  2,  3, 10, 11, 12,  4,  5,  6,  7,  8,  9])

In [ ]:
np.insert(arr4,3,[10,11,12],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])