<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/indexing_slicing_fancy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a[0])    # First element
print(a[2])    # Third element
print(a[-1])   # Last element
print(a[-2])   # Second-last element

# Understanding:
# Indexing is used to access a particular element.
# Python uses zero-based indexing, so the first element has index 0.
# Negative indexing starts from the end.

10
30
60
50


In [2]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(a[:4])       # First four
print(a[-3:])      # Last three
print(a[2:6])      # Index 2 to 5
print(a[::2])      # Every second element
print(a[::-1])     # Reverse

# Understanding:
# Slicing syntax is start : stop : step.
# The start index is included.
# The stop index is excluded.
# Step tells us how many positions to move.
# A step of -1 reverses the array.

[10 20 30 40]
[60 70 80]
[30 40 50 60]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


In [3]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[0])       # First row
print(a[:, 2])    # Third column
print(a[1, 2])    # Element 60
print(a[-1])      # Last row
print(a[:2])      # First two rows
print(a[:, 1:])   # Last two columns
print(a[1:, 1:])  # Sub-matrix

# Understanding:
# In a 2D array, we use [row, column].
# a[row, column] accesses one particular element.
# : means all rows or all columns.
# Slicing can select multiple rows and columns.

[10 20 30]
[30 60 90]
60
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[50 60]
 [80 90]]


In [4]:
a = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)

print("First layer:")
print(a[0])

print("Second layer:")
print(a[1])

print("Element 8:")
print(a[1, 1, 1])

print("First row from both layers:")
print(a[:, 0, :])

print("Second column from every layer:")
print(a[:, :, 1])

# Understanding:
# A 3D array uses three indexes:
# a[layer, row, column].
# The first index selects the layer.
# The second index selects the row.
# The third index selects the column.

Shape: (2, 2, 2)
Dimensions: 3
First layer:
[[1 2]
 [3 4]]
Second layer:
[[5 6]
 [7 8]]
Element 8:
8
First row from both layers:
[[1 2]
 [5 6]]
Second column from every layer:
[[2 4]
 [6 8]]


In [5]:
a = np.array([10, 20, 30, 40, 50, 60, 70])

print(a[[0, 2, 4]])
print(a[[1, 1, 3]])
print(a[[6, 4, 2]])

# Understanding:
# Fancy indexing means selecting elements using a list or array of indexes.
# We can select indexes in any order.
# We can also repeat an index.

[10 30 50]
[20 20 40]
[70 50 30]


In [6]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[[0, 2]])       # First and third rows
print(a[[0, 2], [1, 2]])  # 20 and 90
print(a[1, :])        # 40, 50, 60

# Understanding:
# Fancy indexing allows us to select specific rows or elements.
# It is useful when the required indexes are not continuous.

[[10 20 30]
 [70 80 90]]
[20 90]
[40 50 60]


In [7]:
a = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])

print(a[a > 25])
print(a[a < 30])
print(a[a % 2 == 0])
print(a[a % 2 != 0])
print(a[(a >= 20) & (a <= 40)])

# Understanding:
# Boolean indexing uses True/False conditions to filter data.
# Only elements where the condition is True are returned.
# & means AND when combining NumPy conditions.

[30 35 40 45 50]
[10 15 20 25]
[10 20 30 40 50]
[15 25 35 45]
[20 25 30 35 40]


In [8]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[a > 50])
print(a[a < 40])
print(a[a % 2 == 0])

# Understanding:
# Boolean indexing checks every element against the condition.
# The selected elements are returned as a 1D array.
# Therefore, the original row-column structure is not preserved.

[60 70 80 90]
[10 20 30]
[10 20 30 40 50 60 70 80 90]


In [9]:
a = np.array([10, 20, 30, 40, 50])

b = a[2:]

print("id(a):", id(a))
print("id(b):", id(b))

print("a memory:", a.ctypes.data)
print("b memory:", b.ctypes.data)

print("a.base:", a.base)
print("b.base:", b.base)

b[0] = 999

print("a:", a)
print("b:", b)

# Understanding:
# Slicing an ndarray usually creates a view.
# A view shares the same underlying data with the original array.
# Therefore, changing b can change a.

id(a): 135302771571952
id(b): 135303052207344
a memory: 1050359248
b memory: 1050359264
a.base: None
b.base: [10 20 30 40 50]
a: [ 10  20 999  40  50]
b: [999  40  50]


In [10]:
a = np.array([10, 20, 30, 40, 50])

b = a.view()

print("id(a):", id(a))
print("id(b):", id(b))

print("a memory:", a.ctypes.data)
print("b memory:", b.ctypes.data)

print("a.base:", a.base)
print("b.base:", b.base)

b[0] = 999

print("a:", a)
print("b:", b)

# Understanding:
# .view() creates a new ndarray object that shares the same data.
# Therefore, modifying b also modifies a.
# The main difference from slicing is how the view is created:
# slicing selects a portion, while .view() creates a view of the array.

id(a): 135302771571760
id(b): 135302771562160
a memory: 1045294608
b memory: 1045294608
a.base: None
b.base: [10 20 30 40 50]
a: [999  20  30  40  50]
b: [999  20  30  40  50]


In [11]:
a = np.array([10, 20, 30, 40, 50])

b = a.copy()

print("id(a):", id(a))
print("id(b):", id(b))

print("a memory:", a.ctypes.data)
print("b memory:", b.ctypes.data)

print("a.base:", a.base)
print("b.base:", b.base)

b[2] = 999

print("a:", a)
print("b:", b)

# Understanding:
# .copy() creates a completely independent array.
# It has separate memory.
# Changing b does not change a.

id(a): 135302770327696
id(b): 135302770327792
a memory: 1050359248
b memory: 1055603328
a.base: None
b.base: None
a: [10 20 30 40 50]
b: [ 10  20 999  40  50]


In [12]:
a = np.array([1, 2, 3, 4, 5])

b = a[1:]       # View
c = a.view()    # View
d = a.copy()    # Copy

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

print("a memory:", a.ctypes.data)
print("b memory:", b.ctypes.data)
print("c memory:", c.ctypes.data)
print("d memory:", d.ctypes.data)

print("a.base:", a.base)
print("b.base:", b.base)
print("c.base:", c.base)
print("d.base:", d.base)

b[0] = 100
c[1] = 200
d[2] = 300

print("\nAfter modification:")

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

# Understanding:
# b is a view, so changing b changes a.
# c is also a view, so changing c changes a.
# d is a copy, so changing d does not change a.
# Views share underlying data, while copies have independent data.

a: [1 2 3 4 5]
b: [2 3 4 5]
c: [1 2 3 4 5]
d: [1 2 3 4 5]
a memory: 1045294608
b memory: 1045294616
c memory: 1045294608
d memory: 1055603328
a.base: None
b.base: [1 2 3 4 5]
c.base: [1 2 3 4 5]
d.base: None

After modification:
a: [  1 200   3   4   5]
b: [200   3   4   5]
c: [  1 200   3   4   5]
d: [  1   2 300   4   5]


# Understanding:
#
# 1. id(a) and id(b) are different because a and b are
#    different NumPy ndarray Python objects.
#
# 2. ctypes.data gives the memory address where an array's
#    data begins. A slice can have a different starting address
#    because it may start at a different element, even though
#    it shares the same underlying memory.
#
# 3. a.base is usually None because a is the original array
#    that owns its data.
#
# 4. b.base may point to a because b is a view created from a.
#
# 5. The original/base array generally owns the underlying memory.
#    A view does not own a separate copy of that data.

| Feature                        | Normal Indexing                                           | Fancy Indexing                 | Boolean Indexing           | View                                  | Copy                               |
| ------------------------------ | --------------------------------------------------------- | ------------------------------ | -------------------------- | ------------------------------------- | ---------------------------------- |
| **Purpose**                    | Access element/position                                   | Select specific indexes        | Filter by condition        | Share existing data                   | Create independent data            |
| **Returns**                    | Single or selected data                                   | Multiple elements              | Multiple matching elements | ndarray view                          | New ndarray                        |
| **Shares Memory**              | For a scalar, not an ndarray; basic slicing shares memory | ❌ Generally no                 | ❌ Generally no             | ✅ Yes                                 | ❌ No                               |
| **Creates New ndarray Object** | Usually scalar for single element                         | ✅ Yes                          | ✅ Yes                      | ✅ Yes                                 | ✅ Yes                              |
| **Changes Affect Original**    | Element assignment changes original                       | ❌ Generally no                 | ❌ Generally no             | ✅ Yes                                 | ❌ No                               |
| **Typical Use**                | Access a particular value                                 | Select specific rows/positions | Filter data                | Efficient data access without copying | Safe independent data manipulation |
