<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/integer_datatype_and_memory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr8 = np.array([10, 20, 30, 40, 50], dtype=np.int8)
arr16 = np.array([10, 20, 30, 40, 50], dtype=np.int16)
arr32 = np.array([10, 20, 30, 40, 50], dtype=np.int32)
arr64 = np.array([10, 20, 30, 40, 50], dtype=np.int64)

for arr in [arr8, arr16, arr32, arr64]:
    print("dtype:", arr.dtype)
    print("itemsize:", arr.itemsize, "bytes")
    print("nbytes:", arr.nbytes, "bytes")
    print()

dtype: int8
itemsize: 1 bytes
nbytes: 5 bytes

dtype: int16
itemsize: 2 bytes
nbytes: 10 bytes

dtype: int32
itemsize: 4 bytes
nbytes: 20 bytes

dtype: int64
itemsize: 8 bytes
nbytes: 40 bytes



In [2]:
import numpy as np

arr16 = np.array([10.5, 20.5, 30.5], dtype=np.float16)
arr32 = np.array([10.5, 20.5, 30.5], dtype=np.float32)
arr64 = np.array([10.5, 20.5, 30.5], dtype=np.float64)

obj_arr = np.array(["Python", 100, 3.14, True], dtype=object)

for arr in [arr16, arr32, arr64, obj_arr]:
    print("Array:", arr)
    print("dtype:", arr.dtype)
    print("itemsize:", arr.itemsize)
    print("nbytes:", arr.nbytes)
    print()

Array: [10.5 20.5 30.5]
dtype: float16
itemsize: 2
nbytes: 6

Array: [10.5 20.5 30.5]
dtype: float32
itemsize: 4
nbytes: 12

Array: [10.5 20.5 30.5]
dtype: float64
itemsize: 8
nbytes: 24

Array: ['Python' 100 3.14 True]
dtype: object
itemsize: 8
nbytes: 32



In [3]:
scalar = np.array(10)

print(scalar)
print("shape:", scalar.shape)
print("ndim:", scalar.ndim)
print("size:", scalar.size)

10
shape: ()
ndim: 0
size: 1


In [4]:
vector = np.array([10, 20, 30, 40])

print("shape:", vector.shape)
print("ndim:", vector.ndim)
print("size:", vector.size)

shape: (4,)
ndim: 1
size: 4


In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("size:", matrix.size)

shape: (2, 3)
ndim: 2
size: 6


In [6]:
tensor3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("shape:", tensor3.shape)
print("ndim:", tensor3.ndim)
print("size:", tensor3.size)

shape: (2, 2, 2)
ndim: 3
size: 8


In [7]:
tensor4 = np.zeros((2, 2, 2, 2))

print("shape:", tensor4.shape)
print("ndim:", tensor4.ndim)
print("size:", tensor4.size)

shape: (2, 2, 2, 2)
ndim: 4
size: 16


In [8]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("ndim:", arr.ndim)
print("size:", arr.size)
print("itemsize:", arr.itemsize)
print("nbytes:", arr.nbytes)

dtype: int64
shape: (2, 2, 2)
ndim: 3
size: 8
itemsize: 8
nbytes: 64


In [9]:
np.random.random()

0.576732732841412

In [10]:
np.random.rand(3)

array([0.33669066, 0.42709898, 0.42133734])

In [11]:
np.random.randn(5)

array([ 0.28177184, -1.47160929, -1.41068558, -0.07274805,  0.91170354])

In [12]:
np.random.randint(1, 10, 5)

array([3, 4, 7, 8, 9])

In [13]:
np.random.normal(loc=50, scale=10, size=5)

array([59.64327097, 64.44605756, 52.62592777, 43.54892288, 54.36256519])

In [14]:
import numpy as np

arr = np.arange(1, 11)

print("Original:", arr)

np.random.shuffle(arr)

print("After shuffle:", arr)

Original: [ 1  2  3  4  5  6  7  8  9 10]
After shuffle: [ 2  8  6  1  7  4  3  5  9 10]


In [15]:
arr = np.arange(1, 11)

new_arr = np.random.permutation(arr)

print("Original:", arr)
print("Permutation:", new_arr)

Original: [ 1  2  3  4  5  6  7  8  9 10]
Permutation: [ 3  8  9 10  5  4  7  2  6  1]


In [16]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

In [18]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [21]:
arr = np.array([10, 20, 30, 40, 50])

arr_float32 = arr.astype(np.float32)
arr_float64 = arr.astype(np.float64)
arr_object = arr.astype(object)

print(arr_float32.dtype)
print(arr_float64.dtype)
print(arr_object.dtype)

float32
float64
object


In [22]:
arr8 = np.arange(1000, dtype=np.int8)
arr16 = np.arange(1000, dtype=np.int16)
arr32 = np.arange(1000, dtype=np.int32)
arr64 = np.arange(1000, dtype=np.int64)

In [23]:
arr8 = np.zeros(1000, dtype=np.int8)
arr16 = np.zeros(1000, dtype=np.int16)
arr32 = np.zeros(1000, dtype=np.int32)
arr64 = np.zeros(1000, dtype=np.int64)

for arr in [arr8, arr16, arr32, arr64]:
    print(arr.dtype, arr.itemsize, arr.nbytes)

int8 1 1000
int16 2 2000
int32 4 4000
int64 8 8000


In [24]:
import numpy as np

my_list = [10, 20, 30, 40, 50]

my_array = np.array([10, 20, 30, 40, 50])

In [25]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
print(len(my_list))
print(len(my_array))

5
5


In [27]:
result = [x + 10 for x in my_list]

print(result)

[20, 30, 40, 50, 60]


In [28]:
print([x * 2 for x in my_list])

[20, 40, 60, 80, 100]


In [29]:

print(my_list[2])
print(my_array[2])

30
30


In [30]:
print(my_list[1:4])
print(my_array[1:4])

[20, 30, 40]
[20 30 40]


In [31]:
print(my_array.nbytes)

40


In [32]:
[10, 20, 30] + [40, 50, 60]

[10, 20, 30, 40, 50, 60]