<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/pandastask01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
(1)
import pandas as pd
temperatures = [32, 34, 31, 35, 33]
s1 = pd.Series(temperatures)
print(s1)

0    32
1    34
2    31
3    35
4    33
dtype: int64


In [5]:
(2)
employees = ("Rahul", "Priya", "Arjun", "Sneha", "Kiran")
s2 = pd.Series(employees)
print(s2)

0    Rahul
1    Priya
2    Arjun
3    Sneha
4    Kiran
dtype: object


In [6]:
(3)
product_ids = {101, 102, 103, 104, 105}
s3 = pd.Series(list(product_ids))
print(s3)

0    101
1    102
2    103
3    104
4    105
dtype: int64


In [7]:
(4)
marks = {
    "Python": 85,
    "SQL": 90,
    "Pandas": 88,
    "Statistics": 80}
s4 = pd.Series(marks)
print(s4)

Python        85
SQL           90
Pandas        88
Statistics    80
dtype: int64


In [9]:
(5)
import numpy as np
import pandas as pd
arr1 = np.array([5000, 6000, 4500, 7000, 5500])
arr2 = pd.Series(arr1)
print("Monthly Expenses:")
print(arr2)

Monthly Expenses:
0    5000
1    6000
2    4500
3    7000
4    5500
dtype: int64


In [10]:
(6)
temperatures = [32, 34, 31, 35, 33]
temp_series = pd.Series(temperatures)
print("\nIndex of List Series:")
print(temp_series.index)
print("Values of List Series:")
print(temp_series.values)


Index of List Series:
RangeIndex(start=0, stop=5, step=1)
Values of List Series:
[32 34 31 35 33]


In [11]:
(7)
employees = ("Rahul", "Priya", "Arjun", "Sneha", "Kiran")
employee_series = pd.Series(employees)
print("\nIndex of Tuple Series:")
print(employee_series.index)
print("Values of Tuple Series:")
print(employee_series.values)


Index of Tuple Series:
RangeIndex(start=0, stop=5, step=1)
Values of Tuple Series:
['Rahul' 'Priya' 'Arjun' 'Sneha' 'Kiran']


In [12]:
(8)
marks = {
    "Python": 85,
    "SQL": 90,
    "Pandas": 88}
marks_series = pd.Series(marks)
print("Dictionary Series Index:")
print(marks_series.index)
print("Dictionary Series Values:")
print(marks_series.values)

Dictionary Series Index:
Index(['Python', 'SQL', 'Pandas'], dtype='object')
Dictionary Series Values:
[85 90 88]


In [13]:
(9)
names = ["Rahul", "Priya", "Arjun"]
name_series = pd.Series(names,
    index=["Student1", "Student2", "Student3"])
print("\nCustom Index Series:")
print(name_series)


Custom Index Series:
Student1    Rahul
Student2    Priya
Student3    Arjun
dtype: object


In [14]:
(10)
subjects = {
    "Python": 85,
    "SQL": 90,
    "Pandas": 88
}

subject_series = pd.Series(subjects)

print("\nOnly Values:")
print(subject_series.values)


Only Values:
[85 90 88]


In [15]:
(11)
boolean_list = [True, False, True, True, False]
boolean_series = pd.Series(boolean_list)
print("\nBoolean Series:")
print(boolean_series)


Boolean Series:
0     True
1    False
2     True
3     True
4    False
dtype: bool


In [16]:
(12)
numbers = np.array([10, 20, 30, 40, 50])
number_series = pd.Series(numbers)
print("\nNumPy Series:")
print(number_series)
print("Data Type:")
print(number_series.dtype)


NumPy Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64
Data Type:
int64


In [17]:
(13)
import pandas as pd

data = [
    [101, 'Rahul', 85],
    [102, 'Priya', 90],
    [103, 'Arjun', 78],
    [104, 'Sneha', 88]
]

df = pd.DataFrame(data)

print(df)

     0      1   2
0  101  Rahul  85
1  102  Priya  90
2  103  Arjun  78
3  104  Sneha  88


In [18]:
(14)
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet'],
    'Price': [50000, 20000, 30000],
    'Quantity': [2, 5, 3]
}

df = pd.DataFrame(data)

print(df)

  Product  Price  Quantity
0  Laptop  50000         2
1  Mobile  20000         5
2  Tablet  30000         3


In [19]:
(15)
import numpy as np
data = np.array([
    [101, 25, 50000],
    [102, 30, 60000],
    [103, 28, 55000]
])

df = pd.DataFrame(data)

print(df)

     0   1      2
0  101  25  50000
1  102  30  60000
2  103  28  55000


In [20]:
(16)
df = pd.DataFrame(
    data,
    columns=['Student_ID', 'Name', 'Score']
)

print(df)

   Student_ID  Name  Score
0         101    25  50000
1         102    30  60000
2         103    28  55000


In [21]:
(17)
data = np.array([
    [101, 25, 50000],
    [102, 30, 60000],
    [103, 28, 55000]
])

df = pd.DataFrame(
    data,
    columns=['Employee_ID', 'Age', 'Salary']
)

print(df)

   Employee_ID  Age  Salary
0          101   25   50000
1          102   30   60000
2          103   28   55000


In [22]:
(18)
print(df.shape)

(3, 3)


In [23]:
(19)
print(df.columns)

Index(['Employee_ID', 'Age', 'Salary'], dtype='object')


In [24]:
(20)
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [25]:
(21)
print("Shape:", df.shape)
print("Columns:", df.columns)
print("Index:", df.index)

Shape: (3, 3)
Columns: Index(['Employee_ID', 'Age', 'Salary'], dtype='object')
Index: RangeIndex(start=0, stop=3, step=1)


observation & generalization

In [28]:
(22)
marks = {
    'Python': 85,
    'SQL': 90,
    'Pandas': 88
}
s = pd.Series(marks)
df = s.to_frame(name='Marks')
print(df)

        Marks
Python     85
SQL        90
Pandas     88


In [30]:
(23)
arr = np.array([10, 20, 30, 40])
s2 = pd.Series(arr)
df2 = s2.to_frame(name='Values')
print(df2)

   Values
0      10
1      20
2      30
3      40


In [31]:
(24)
print("Index:", df2.index)
print("Columns:", df2.columns)

Index: RangeIndex(start=0, stop=4, step=1)
Columns: Index(['Values'], dtype='object')


In [32]:
(25)
print("Rows and Columns:", df2.shape)

Rows and Columns: (4, 1)


In [33]:
(26)
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)
print(type(s))

0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>


In [34]:
(27)
df = pd.DataFrame({
    'Name': ['Rahul', 'Priya', 'Arjun'],
    'Age': [22, 24, 21]
})

print(df)
print(type(df))

    Name  Age
0  Rahul   22
1  Priya   24
2  Arjun   21
<class 'pandas.core.frame.DataFrame'>


In [35]:
(28)
print("Series:")
print(s)

print("\nDataFrame:")
print(df)


Series:
0    10
1    20
2    30
3    40
dtype: int64

DataFrame:
    Name  Age
0  Rahul   22
1  Priya   24
2  Arjun   21


In [36]:
(29)
s = pd.Series([100, 200, 300, 400])

print(s)
print("Index:", s.index)

0    100
1    200
2    300
3    400
dtype: int64
Index: RangeIndex(start=0, stop=4, step=1)


In [37]:
(30)
df = pd.DataFrame({
    'Name': ['Rahul', 'Priya', 'Arjun'],
    'Age': [22, 24, 21]
})

print(df)

    Name  Age
0  Rahul   22
1  Priya   24
2  Arjun   21
